/* Generated by            cobc 1.1.0 */
/* Generated from          orbits.cob */
/* Generated at            set 14 2015 22:22:43 CEST */
/* OpenCOBOL build date    Sep 14 2015 19:29:23 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc --free -x -C orbits.cob */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"orbits.cob"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "orbits.c.h"

static void
cob_decimal_set_int (cob_decimal *d, const int n)
{
	mpz_set_si (d->value, n);
	d->scale = 0;
}

/* Function prototypes */

int ORBITS ();
static int ORBITS_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (ORBITS ());
}

/* Functions */

int
ORBITS ()
{
  return ORBITS_ (0);
}

static int
ORBITS_ (const int entry)
{
  /* Local variables */
  #include "orbits.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, NULL, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	cob_close (h_ENTRADA, 0, NULL);
  	cob_close (h_SORTIDA, 0, NULL);
  	mpz_clear (d0.value);
  	d0.scale = 0;
  	mpz_clear (d1.value);
  	d1.scale = 0;
  	mpz_clear (d2.value);
  	d2.scale = 0;
  	mpz_clear (d3.value);
  	d3.scale = 0;
  	mpz_clear (d4.value);
  	d4.scale = 0;
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      /* Initialize decimal numbers */
      cob_decimal_init (&d0);
      cob_decimal_init (&d1);
      cob_decimal_init (&d2);
      cob_decimal_init (&d3);
      cob_decimal_init (&d4);

      (*(int *) (b_1)) = 0;

      if (!h_ENTRADA)
      {
        h_ENTRADA = cob_malloc (sizeof(cob_file));
      }
      h_ENTRADA->select_name = (const char *)"ENTRADA";
      h_ENTRADA->file_status = h_ENTRADA_status;
      memset (h_ENTRADA_status, '0', 2);
      h_ENTRADA->assign = &c_1;
      h_ENTRADA->record = &f_14;
      h_ENTRADA->record_size = NULL;
      h_ENTRADA->record_min = 0;
      h_ENTRADA->record_max = 33;
      h_ENTRADA->nkeys = 0;
      h_ENTRADA->keys = NULL;
      h_ENTRADA->file = NULL;
      h_ENTRADA->organization = 1;
      h_ENTRADA->access_mode = 1;
      h_ENTRADA->lock_mode = 0;
      h_ENTRADA->open_mode = 0;
      h_ENTRADA->flag_optional = 0;
      h_ENTRADA->last_open_mode = 0;
      h_ENTRADA->special = 0;
      h_ENTRADA->flag_nonexistent = 0;
      h_ENTRADA->flag_end_of_file = 0;
      h_ENTRADA->flag_begin_of_file = 0;
      h_ENTRADA->flag_first_read = 0;
      h_ENTRADA->flag_read_done = 0;
      h_ENTRADA->flag_select_features = 0;
      h_ENTRADA->flag_needs_nl = 0;
      h_ENTRADA->flag_needs_top = 0;
      h_ENTRADA->file_version = 0;
      if (!h_SORTIDA)
      {
        h_SORTIDA = cob_malloc (sizeof(cob_file));
      }
      h_SORTIDA->select_name = (const char *)"SORTIDA";
      h_SORTIDA->file_status = h_SORTIDA_status;
      memset (h_SORTIDA_status, '0', 2);
      h_SORTIDA->assign = &c_2;
      h_SORTIDA->record = &f_16;
      h_SORTIDA->record_size = NULL;
      h_SORTIDA->record_min = 0;
      h_SORTIDA->record_max = 80;
      h_SORTIDA->nkeys = 0;
      h_SORTIDA->keys = NULL;
      h_SORTIDA->file = NULL;
      h_SORTIDA->organization = 1;
      h_SORTIDA->access_mode = 1;
      h_SORTIDA->lock_mode = 0;
      h_SORTIDA->open_mode = 0;
      h_SORTIDA->flag_optional = 0;
      h_SORTIDA->last_open_mode = 0;
      h_SORTIDA->special = 0;
      h_SORTIDA->flag_nonexistent = 0;
      h_SORTIDA->flag_end_of_file = 0;
      h_SORTIDA->flag_begin_of_file = 0;
      h_SORTIDA->flag_first_read = 0;
      h_SORTIDA->flag_read_done = 0;
      h_SORTIDA->flag_select_features = 0;
      h_SORTIDA->flag_needs_nl = 0;
      h_SORTIDA->flag_needs_top = 0;
      h_SORTIDA->file_version = 0;

      initialized = 1;
    }

  /* Allocate LOCAL storage */
  b_17 = cob_malloc (24);
  b_21 = cob_malloc (24);
  b_25 = cob_malloc (24);
  b_29 = cob_malloc (24);
  b_33 = cob_malloc (24);
  b_37 = cob_malloc (24);
  b_41 = cob_malloc (24);
  b_45 = cob_malloc (8);
  b_46 = cob_malloc (4);
  b_47 = cob_malloc (8);
  b_48 = cob_malloc (8);
  b_49 = cob_malloc (8);
  b_50 = cob_malloc (8);
  b_51 = cob_malloc (8);
  b_52 = cob_malloc (4);
  b_53 = cob_malloc (1);
  b_55 = cob_malloc (56);
  b_61 = cob_malloc (56);
  b_67 = cob_malloc (56);

  /* Initialialize LOCAL storage */
  {double temp = 0.0; memcpy (b_17, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_17 + 8, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_17 + 16, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_21, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_21 + 8, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_21 + 16, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_25, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_25 + 8, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_25 + 16, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_29, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_29 + 8, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_29 + 16, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_33, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_33 + 8, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_33 + 16, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_37, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_37 + 8, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_37 + 16, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_41, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_41 + 8, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_41 + 16, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_45, (char *)&temp, sizeof(temp));}
  memset (b_46, 0, 4);
  {double temp = 0.0; memcpy (b_47, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_48, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_49, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_50, (char *)&temp, sizeof(temp));}
  {double temp = 0.0; memcpy (b_51, (char *)&temp, sizeof(temp));}
  memset (b_52, 0, 4);
  *(unsigned char *)(b_53) = 32;
  memcpy (b_55, "X", 1);
  memset (b_55 + 1, 32, 17);
  *(unsigned char *)(b_55 + 18) = 32;
  memcpy (b_55 + 19, "Y", 1);
  memset (b_55 + 19 + 1, 32, 17);
  *(unsigned char *)(b_55 + 37) = 32;
  memcpy (b_55 + 38, "Z", 1);
  memset (b_55 + 38 + 1, 32, 17);
  memset (b_61, 61, 18);
  *(unsigned char *)(b_61 + 18) = 32;
  memset (b_61 + 19, 61, 18);
  *(unsigned char *)(b_61 + 37) = 32;
  memset (b_61 + 38, 61, 18);
  memset (b_67, 48, 18);
  *(unsigned char *)(b_67 + 18) = 32;
  memset (b_67 + 19, 48, 18);
  *(unsigned char *)(b_67 + 37) = 32;
  memset (b_67 + 38, 48, 18);

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry ORBITS */

  l_2:;

  /* MAIN SECTION */

  /* BEGIN */

  /* orbits.cob:97: DISPLAY */
  {
    cob_display (0, 1, 1, &c_3);
  }
  /* orbits.cob:98: MOVE */
  {
    cob_move (&c_4, (f_45.data = b_45, &f_45));
  }
  /* orbits.cob:99: OPEN */
  {
    cob_exception_code = 0;
    {
      cob_open (h_ENTRADA, 1, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_14;
        goto l_1;
        l_14:
        frame_ptr--;
      }
  }
  /* orbits.cob:100: OPEN */
  {
    cob_exception_code = 0;
    {
      cob_open (h_SORTIDA, 2, 1, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_15;
        goto l_1;
        l_15:
        frame_ptr--;
      }
  }
  /* orbits.cob:101: PERFORM */
  {
    /* PERFORM LLISTAR-CAPCALERA */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address = &&l_16;
    goto l_12;
    l_16:
    frame_ptr--;
  }
  /* orbits.cob:102: PERFORM */
  {
    /* PERFORM CARREGAR-DADES */
    frame_ptr++;
    frame_ptr->perform_through = 10;
    frame_ptr->return_address = &&l_17;
    goto l_10;
    l_17:
    frame_ptr--;
  }
  /* orbits.cob:103: PERFORM */
  {
    cob_setswp_s32_binary (b_46, 1);
    while (1)
      {
        if (((int)cob_cmpswp_s32_binary (b_46, ((int)COB_BSWAP_32(*(int *)(b_52)))) == 0))
          break;
        /* PERFORM FER-CALCULS */
        frame_ptr++;
        frame_ptr->perform_through = 5;
        frame_ptr->return_address = &&l_18;
        goto l_5;
        l_18:
        frame_ptr--;
        cob_addswp_s32_binary (b_46, 1);
      }
  }
  /* orbits.cob:104: CLOSE */
  {
    cob_exception_code = 0;
    {
      cob_close (h_ENTRADA, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_19;
        goto l_1;
        l_19:
        frame_ptr--;
      }
  }
  /* orbits.cob:105: CLOSE */
  {
    cob_exception_code = 0;
    {
      cob_close (h_SORTIDA, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_20;
        goto l_1;
        l_20:
        frame_ptr--;
      }
  }
  /* orbits.cob:106: DISPLAY */
  {
    cob_display (0, 1, 1, &c_5);
  }
  /* orbits.cob:107: STOP */
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* FER-CALCULS */

  l_5:;
  /* orbits.cob:111: PERFORM */
  {
    /* PERFORM CALCULA-ACCELERACIO */
    frame_ptr++;
    frame_ptr->perform_through = 6;
    frame_ptr->return_address = &&l_21;
    goto l_6;
    l_21:
    frame_ptr--;
  }
  /* orbits.cob:112: PERFORM */
  {
    /* PERFORM APLICA-VELOCITAT */
    frame_ptr++;
    frame_ptr->perform_through = 8;
    frame_ptr->return_address = &&l_22;
    goto l_8;
    l_22:
    frame_ptr--;
  }
  /* orbits.cob:113: PERFORM */
  {
    /* PERFORM APLICA-POSICIO */
    frame_ptr++;
    frame_ptr->perform_through = 9;
    frame_ptr->return_address = &&l_23;
    goto l_9;
    l_23:
    frame_ptr--;
  }
  /* orbits.cob:114: MOVE */
  {
    cob_move ((f_18.data = b_17, &f_18), (f_68.data = b_67, &f_68));
  }
  /* orbits.cob:115: MOVE */
  {
    cob_move ((f_19.data = b_17 + 8, &f_19), (f_70.data = b_67 + 19, &f_70));
  }
  /* orbits.cob:116: MOVE */
  {
    cob_move ((f_20.data = b_17 + 16, &f_20), (f_72.data = b_67 + 38, &f_72));
  }
  /* orbits.cob:117: MOVE */
  {
    cob_move ((f_67.data = b_67, &f_67), &f_15);
  }
  /* orbits.cob:118: WRITE */
  cob_exception_code = 0;
  {
    cob_write (h_SORTIDA, &f_15, 2162689, NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_24;
      goto l_1;
      l_24:
      frame_ptr--;
    }

  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address;

  /* CALCULA-ACCELERACIO */

  l_6:;
  /* orbits.cob:122: MOVE */
  {
    memcpy (b_41, b_17, 24);
  }
  /* orbits.cob:123: SUBTRACT */
  {
    cob_sub ((f_42.data = b_41, &f_42), (f_22.data = b_21, &f_22), 2);
  }
  /* orbits.cob:124: SUBTRACT */
  {
    cob_sub ((f_43.data = b_41 + 8, &f_43), (f_23.data = b_21 + 8, &f_23), 2);
  }
  /* orbits.cob:125: SUBTRACT */
  {
    cob_sub ((f_44.data = b_41 + 16, &f_44), (f_24.data = b_21 + 16, &f_24), 2);
  }
  /* orbits.cob:126: PERFORM */
  {
    /* PERFORM CALCULA-R */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address = &&l_25;
    goto l_7;
    l_25:
    frame_ptr--;
  }
  /* orbits.cob:127: COMPUTE */
  {
    {
      {
        cob_decimal_set_int (&d0, 0);
        cob_decimal_set_field (&d4, (f_45.data = b_45, &f_45));
        cob_decimal_sub (&d0, &d4);
        cob_decimal_set_field (&d3, (f_47.data = b_47, &f_47));
        cob_decimal_mul (&d0, &d3);
        cob_decimal_set_field (&d2, (f_48.data = b_48, &f_48));
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_field (&d1, (f_49.data = b_49, &f_49));
        cob_decimal_set_int (&d2, 3);
        cob_decimal_pow (&d1, &d2);
        cob_decimal_div (&d0, &d1);
        cob_decimal_get_field (&d0, (f_50.data = b_50, &f_50), 2);
      }
    }
  }
  /* orbits.cob:128: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_50.data = b_50, &f_50));
        cob_decimal_set_field (&d2, (f_42.data = b_41, &f_42));
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_field (&d1, (f_47.data = b_47, &f_47));
        cob_decimal_div (&d0, &d1);
        cob_decimal_get_field (&d0, (f_34.data = b_33, &f_34), 2);
      }
    }
  }
  /* orbits.cob:129: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_50.data = b_50, &f_50));
        cob_decimal_set_field (&d2, (f_43.data = b_41 + 8, &f_43));
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_field (&d1, (f_47.data = b_47, &f_47));
        cob_decimal_div (&d0, &d1);
        cob_decimal_get_field (&d0, (f_35.data = b_33 + 8, &f_35), 2);
      }
    }
  }
  /* orbits.cob:130: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_50.data = b_50, &f_50));
        cob_decimal_set_field (&d2, (f_44.data = b_41 + 16, &f_44));
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_field (&d1, (f_47.data = b_47, &f_47));
        cob_decimal_div (&d0, &d1);
        cob_decimal_get_field (&d0, (f_36.data = b_33 + 16, &f_36), 2);
      }
    }
  }
  /* orbits.cob:131: COMPUTE */
  {
    {
      {
        cob_decimal_set_int (&d0, -1);
        cob_decimal_set_field (&d3, (f_50.data = b_50, &f_50));
        cob_decimal_mul (&d0, &d3);
        cob_decimal_set_field (&d2, (f_42.data = b_41, &f_42));
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_field (&d1, (f_48.data = b_48, &f_48));
        cob_decimal_div (&d0, &d1);
        cob_decimal_get_field (&d0, (f_38.data = b_37, &f_38), 2);
      }
    }
  }
  /* orbits.cob:132: COMPUTE */
  {
    {
      {
        cob_decimal_set_int (&d0, -1);
        cob_decimal_set_field (&d3, (f_50.data = b_50, &f_50));
        cob_decimal_mul (&d0, &d3);
        cob_decimal_set_field (&d2, (f_43.data = b_41 + 8, &f_43));
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_field (&d1, (f_48.data = b_48, &f_48));
        cob_decimal_div (&d0, &d1);
        cob_decimal_get_field (&d0, (f_39.data = b_37 + 8, &f_39), 2);
      }
    }
  }
  /* orbits.cob:133: COMPUTE */
  {
    {
      {
        cob_decimal_set_int (&d0, -1);
        cob_decimal_set_field (&d3, (f_50.data = b_50, &f_50));
        cob_decimal_mul (&d0, &d3);
        cob_decimal_set_field (&d2, (f_44.data = b_41 + 16, &f_44));
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_field (&d1, (f_48.data = b_48, &f_48));
        cob_decimal_div (&d0, &d1);
        cob_decimal_get_field (&d0, (f_40.data = b_37 + 16, &f_40), 2);
      }
    }
  }

  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address;

  /* CALCULA-R */

  l_7:;
  /* orbits.cob:137: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, cob_intr_sqrt (cob_intr_binop (cob_intr_binop (cob_intr_binop ((f_42.data = b_41, &f_42), 42, (f_42.data = b_41, &f_42)), 43, cob_intr_binop ((f_43.data = b_41 + 8, &f_43), 42, (f_43.data = b_41 + 8, &f_43))), 43, cob_intr_binop ((f_44.data = b_41 + 16, &f_44), 42, (f_44.data = b_41 + 16, &f_44)))));
        cob_decimal_get_field (&d0, (f_49.data = b_49, &f_49), 2);
      }
    }
  }

  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address;

  /* APLICA-VELOCITAT */

  l_8:;
  /* orbits.cob:144: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_26.data = b_25, &f_26));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_34.data = b_33, &f_34));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_26.data = b_25, &f_26), 2);
      }
    }
  }
  /* orbits.cob:145: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_27.data = b_25 + 8, &f_27));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_35.data = b_33 + 8, &f_35));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_27.data = b_25 + 8, &f_27), 2);
      }
    }
  }
  /* orbits.cob:146: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_28.data = b_25 + 16, &f_28));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_36.data = b_33 + 16, &f_36));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_28.data = b_25 + 16, &f_28), 2);
      }
    }
  }
  /* orbits.cob:147: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_30.data = b_29, &f_30));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_38.data = b_37, &f_38));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_30.data = b_29, &f_30), 2);
      }
    }
  }
  /* orbits.cob:148: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_31.data = b_29 + 8, &f_31));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_39.data = b_37 + 8, &f_39));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_31.data = b_29 + 8, &f_31), 2);
      }
    }
  }
  /* orbits.cob:149: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_32.data = b_29 + 16, &f_32));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_40.data = b_37 + 16, &f_40));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_32.data = b_29 + 16, &f_32), 2);
      }
    }
  }

  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address;

  /* APLICA-POSICIO */

  l_9:;
  /* orbits.cob:153: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_18.data = b_17, &f_18));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_26.data = b_25, &f_26));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_18.data = b_17, &f_18), 2);
      }
    }
  }
  /* orbits.cob:154: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_19.data = b_17 + 8, &f_19));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_27.data = b_25 + 8, &f_27));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_19.data = b_17 + 8, &f_19), 2);
      }
    }
  }
  /* orbits.cob:155: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_20.data = b_17 + 16, &f_20));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_28.data = b_25 + 16, &f_28));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_20.data = b_17 + 16, &f_20), 2);
      }
    }
  }
  /* orbits.cob:156: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_22.data = b_21, &f_22));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_30.data = b_29, &f_30));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_22.data = b_21, &f_22), 2);
      }
    }
  }
  /* orbits.cob:157: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_23.data = b_21 + 8, &f_23));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_31.data = b_29 + 8, &f_31));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_23.data = b_21 + 8, &f_23), 2);
      }
    }
  }
  /* orbits.cob:158: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, (f_24.data = b_21 + 16, &f_24));
        cob_decimal_set_field (&d1, (f_51.data = b_51, &f_51));
        cob_decimal_set_field (&d2, (f_32.data = b_29 + 16, &f_32));
        cob_decimal_mul (&d1, &d2);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_24.data = b_21 + 16, &f_24), 2);
      }
    }
  }

  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address;

  /* CARREGAR-DADES */

  l_10:;
  /* orbits.cob:162: PERFORM */
  {
    /* PERFORM LLEGIR-ENTRADA */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address = &&l_26;
    goto l_11;
    l_26:
    frame_ptr--;
  }
  /* orbits.cob:163: MOVE */
  {
    cob_move (&f_6, (f_18.data = b_17, &f_18));
  }
  /* orbits.cob:164: MOVE */
  {
    cob_move (&f_8, (f_19.data = b_17 + 8, &f_19));
  }
  /* orbits.cob:165: MOVE */
  {
    cob_move (&f_7, (f_20.data = b_17 + 16, &f_20));
  }
  /* orbits.cob:166: PERFORM */
  {
    /* PERFORM LLEGIR-ENTRADA */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address = &&l_27;
    goto l_11;
    l_27:
    frame_ptr--;
  }
  /* orbits.cob:167: MOVE */
  {
    cob_move (&f_6, (f_26.data = b_25, &f_26));
  }
  /* orbits.cob:168: MOVE */
  {
    cob_move (&f_8, (f_27.data = b_25 + 8, &f_27));
  }
  /* orbits.cob:169: MOVE */
  {
    cob_move (&f_7, (f_28.data = b_25 + 16, &f_28));
  }
  /* orbits.cob:170: PERFORM */
  {
    /* PERFORM LLEGIR-ENTRADA */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address = &&l_28;
    goto l_11;
    l_28:
    frame_ptr--;
  }
  /* orbits.cob:171: MOVE */
  {
    cob_move (&f_10, (f_47.data = b_47, &f_47));
  }
  /* orbits.cob:172: PERFORM */
  {
    /* PERFORM LLEGIR-ENTRADA */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address = &&l_29;
    goto l_11;
    l_29:
    frame_ptr--;
  }
  /* orbits.cob:173: MOVE */
  {
    cob_move (&f_6, (f_22.data = b_21, &f_22));
  }
  /* orbits.cob:174: MOVE */
  {
    cob_move (&f_8, (f_23.data = b_21 + 8, &f_23));
  }
  /* orbits.cob:175: MOVE */
  {
    cob_move (&f_7, (f_24.data = b_21 + 16, &f_24));
  }
  /* orbits.cob:176: PERFORM */
  {
    /* PERFORM LLEGIR-ENTRADA */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address = &&l_30;
    goto l_11;
    l_30:
    frame_ptr--;
  }
  /* orbits.cob:177: MOVE */
  {
    cob_move (&f_6, (f_30.data = b_29, &f_30));
  }
  /* orbits.cob:178: MOVE */
  {
    cob_move (&f_8, (f_31.data = b_29 + 8, &f_31));
  }
  /* orbits.cob:179: MOVE */
  {
    cob_move (&f_7, (f_32.data = b_29 + 16, &f_32));
  }
  /* orbits.cob:180: PERFORM */
  {
    /* PERFORM LLEGIR-ENTRADA */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address = &&l_31;
    goto l_11;
    l_31:
    frame_ptr--;
  }
  /* orbits.cob:181: MOVE */
  {
    cob_move (&f_10, (f_48.data = b_48, &f_48));
  }
  /* orbits.cob:182: PERFORM */
  {
    /* PERFORM LLEGIR-ENTRADA */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address = &&l_32;
    goto l_11;
    l_32:
    frame_ptr--;
  }
  /* orbits.cob:183: MOVE */
  {
    cob_move (&f_12, (f_51.data = b_51, &f_51));
  }
  /* orbits.cob:184: MOVE */
  {
    cob_move (&f_13, (f_52.data = b_52, &f_52));
  }

  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address;

  /* LLEGIR-ENTRADA */

  l_11:;
  /* orbits.cob:188: READ */
  cob_exception_code = 0;
  {
    cob_read (h_ENTRADA, 0, NULL, 1);
  }
  if (unlikely(cob_exception_code != 0))
    {
      if (cob_exception_code == 0x0501)
        {
          {
            /* orbits.cob:190: SET */
            {
              *(b_53) = 83;
            }
            /* orbits.cob:191: GO TO */
            {
              goto l_13;
            }
          }
        }
      else
        {
          /* PERFORM Default Error Handler */
          frame_ptr++;
          frame_ptr->perform_through = 1;
          frame_ptr->return_address = &&l_33;
          goto l_1;
          l_33:
          frame_ptr--;
        }
    }

  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address;

  /* LLISTAR-CAPCALERA */

  l_12:;
  /* orbits.cob:196: MOVE */
  {
    cob_move ((f_55.data = b_55, &f_55), &f_15);
  }
  /* orbits.cob:197: WRITE */
  cob_exception_code = 0;
  {
    cob_write (h_SORTIDA, &f_15, 2162689, NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_34;
      goto l_1;
      l_34:
      frame_ptr--;
    }
  /* orbits.cob:198: MOVE */
  {
    cob_move ((f_61.data = b_61, &f_61), &f_15);
  }
  /* orbits.cob:199: WRITE */
  cob_exception_code = 0;
  {
    cob_write (h_SORTIDA, &f_15, 2162689, NULL);
  }
  if (unlikely(cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      frame_ptr->perform_through = 1;
      frame_ptr->return_address = &&l_35;
      goto l_1;
      l_35:
      frame_ptr--;
    }

  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address;

  /* ABORT-ARXIU-ENTRADA */

  l_13:;
  /* orbits.cob:204: DISPLAY */
  {
    cob_display (0, 1, 1, &c_6);
  }
  /* orbits.cob:205: CLOSE */
  {
    cob_exception_code = 0;
    {
      cob_close (h_ENTRADA, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_36;
        goto l_1;
        l_36:
        frame_ptr--;
      }
  }
  /* orbits.cob:206: CLOSE */
  {
    cob_exception_code = 0;
    {
      cob_close (h_SORTIDA, 0, NULL);
    }
    if (unlikely(cob_exception_code != 0))
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        frame_ptr->perform_through = 1;
        frame_ptr->return_address = &&l_37;
        goto l_1;
        l_37:
        frame_ptr--;
      }
  }
  /* orbits.cob:207: STOP */
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* Program exit */

  /* Deallocate LOCAL storage */
  if (b_67) {
  	free (b_67);
  	b_67 = NULL;
  }
  if (b_61) {
  	free (b_61);
  	b_61 = NULL;
  }
  if (b_55) {
  	free (b_55);
  	b_55 = NULL;
  }
  if (b_53) {
  	free (b_53);
  	b_53 = NULL;
  }
  if (b_52) {
  	free (b_52);
  	b_52 = NULL;
  }
  if (b_51) {
  	free (b_51);
  	b_51 = NULL;
  }
  if (b_50) {
  	free (b_50);
  	b_50 = NULL;
  }
  if (b_49) {
  	free (b_49);
  	b_49 = NULL;
  }
  if (b_48) {
  	free (b_48);
  	b_48 = NULL;
  }
  if (b_47) {
  	free (b_47);
  	b_47 = NULL;
  }
  if (b_46) {
  	free (b_46);
  	b_46 = NULL;
  }
  if (b_45) {
  	free (b_45);
  	b_45 = NULL;
  }
  if (b_41) {
  	free (b_41);
  	b_41 = NULL;
  }
  if (b_37) {
  	free (b_37);
  	b_37 = NULL;
  }
  if (b_33) {
  	free (b_33);
  	b_33 = NULL;
  }
  if (b_29) {
  	free (b_29);
  	b_29 = NULL;
  }
  if (b_25) {
  	free (b_25);
  	b_25 = NULL;
  }
  if (b_21) {
  	free (b_21);
  	b_21 = NULL;
  }
  if (b_17) {
  	free (b_17);
  	b_17 = NULL;
  }

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));


  /* Default Error Handler */

  l_1:;

  if (!(cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_default_error_handle ();
  	cob_stop_run (1);
  }

  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address;

  cob_fatal_error (COB_FERROR_CODEGEN);

}

/* End functions */

