/* Generated by            cobc 1.1.0 */
/* Generated from          orbits.cob */
/* Generated at            set 14 2015 22:22:43 CEST */
/* OpenCOBOL build date    Sep 14 2015 19:29:23 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc --free -x -C orbits.cob */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Storage */

/* PROGRAM-ID : ORBITS */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */
static unsigned char b_14[33] __attribute__((aligned));	/* ENTRADA_record */
static unsigned char b_16[80] __attribute__((aligned));	/* SORTIDA_record */

/* End of storage */


/* Attributes */

static const cob_field_attr a_1 = {33, 0, 0, 0, NULL};
static const cob_field_attr a_2 = {20, 18, 9, 1, NULL};
static const cob_field_attr a_3 = {36, 17, 4, 0, "Z\015\000\000\000.\001\000\000\0009\004\000\000\000"};
static const cob_field_attr a_4 = {1, 0, 0, 0, NULL};
static const cob_field_attr a_5 = {36, 10, 0, 1, "+\001\000\000\0009\012\000\000\000"};
static const cob_field_attr a_6 = {17, 9, 0, 33, NULL};

/* Fields */

/* PROGRAM-ID : ORBITS */
static cob_field f_6	= {11, b_14, &a_5};	/* I-X-COORD */
static cob_field f_7	= {11, b_14 + 11, &a_5};	/* I-Z-COORD */
static cob_field f_8	= {11, b_14 + 22, &a_5};	/* I-Y-COORD */
static cob_field f_10	= {11, b_14, &a_5};	/* I-MASS */
static cob_field f_12	= {11, b_14, &a_5};	/* I-INTERVAL */
static cob_field f_13	= {11, b_14 + 11, &a_5};	/* I-INCREMENT */
static cob_field f_14	= {33, b_14, &a_1};	/* ENTRADA_record */
static cob_field f_15	= {80, b_16, &a_1};	/* LIN-SORTIDA */
static cob_field f_16	= {80, b_16, &a_1};	/* SORTIDA_record */
static cob_field f_18	= {8, NULL, &a_2};	/* X */
static cob_field f_19	= {8, NULL, &a_2};	/* Y */
static cob_field f_20	= {8, NULL, &a_2};	/* Z */
static cob_field f_22	= {8, NULL, &a_2};	/* X */
static cob_field f_23	= {8, NULL, &a_2};	/* Y */
static cob_field f_24	= {8, NULL, &a_2};	/* Z */
static cob_field f_26	= {8, NULL, &a_2};	/* X */
static cob_field f_27	= {8, NULL, &a_2};	/* Y */
static cob_field f_28	= {8, NULL, &a_2};	/* Z */
static cob_field f_30	= {8, NULL, &a_2};	/* X */
static cob_field f_31	= {8, NULL, &a_2};	/* Y */
static cob_field f_32	= {8, NULL, &a_2};	/* Z */
static cob_field f_34	= {8, NULL, &a_2};	/* X */
static cob_field f_35	= {8, NULL, &a_2};	/* Y */
static cob_field f_36	= {8, NULL, &a_2};	/* Z */
static cob_field f_38	= {8, NULL, &a_2};	/* X */
static cob_field f_39	= {8, NULL, &a_2};	/* Y */
static cob_field f_40	= {8, NULL, &a_2};	/* Z */
static cob_field f_42	= {8, NULL, &a_2};	/* X */
static cob_field f_43	= {8, NULL, &a_2};	/* Y */
static cob_field f_44	= {8, NULL, &a_2};	/* Z */
static cob_field f_45	= {8, NULL, &a_2};	/* G */
static cob_field f_47	= {8, NULL, &a_2};	/* M1 */
static cob_field f_48	= {8, NULL, &a_2};	/* M2 */
static cob_field f_49	= {8, NULL, &a_2};	/* R */
static cob_field f_50	= {8, NULL, &a_2};	/* COEF */
static cob_field f_51	= {8, NULL, &a_2};	/* DT */
static cob_field f_52	= {4, NULL, &a_6};	/* NINCR */
static cob_field f_55	= {56, NULL, &a_4};	/* LIN-CAP1 */
static cob_field f_61	= {56, NULL, &a_4};	/* LIN-CAP2 */
static cob_field f_67	= {56, NULL, &a_4};	/* LIN-DET */
static cob_field f_68	= {18, NULL, &a_3};	/* X-D */
static cob_field f_70	= {18, NULL, &a_3};	/* Y-D */
static cob_field f_72	= {18, NULL, &a_3};	/* Z-D */

/* End of fields */

/* Constants */
static cob_field c_1	= {11, (unsigned char *)"entrada.dat", &a_1};
static cob_field c_2	= {11, (unsigned char *)"sortida.lst", &a_1};
static cob_field c_3	= {13, (unsigned char *)"*** INICI ***", &a_1};
static cob_field c_4	= {8, (unsigned char *)"6.67E-11", &a_1};
static cob_field c_5	= {13, (unsigned char *)"*** FINAL ***", &a_1};
static cob_field c_6	= {33, (unsigned char *)"ERROR DE FORMAT A ARXIU D'ENTRADA", &a_1};

