$JOB COMPILE AND EXECUTE ORBIT DEMO
.COMPIL/Q ORB,ORB.LS<ORB
.COMPIL/Q GRAVF,GRAVF.LS<GRAVF
.COMPIL/Q MODUL,MODUL.LS<MODUL
.COMPIL/Q VECSUB,VECSUB.LS<VECSUB
.COMPIL/Q VECINV,VECINV.LS<VECINV
.COMPIL/Q VECMUL,VECMUL.LS<VECMUL
.LOAD/S ORB,ORB.MP<ORB,GRAVF,VECMUL,MODUL,VECSUB,VECINV/G$
*EARTH.DA/4
*DSK:OUT.LS</3$
$END
